import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { ApiClient } from "../api-client.js";
import { Config } from "../config.js";
import { registerAuthTools } from "./auth.js";
import { registerUserTools } from "./users.js";
import { registerTeamTools } from "./teams.js";
import { registerProjectTools } from "./projects.js";
import { registerUserRoleTools } from "./user-roles.js";
import { registerContactFieldTools } from "./contact-fields.js";
import { registerContactTagTools } from "./contact-tags.js";
import { registerOrderFieldTools } from "./order-fields.js";
import { registerOrderTagTools } from "./order-tags.js";
import { registerContactTools } from "./contacts.js";
import { registerOrderTools } from "./orders.js";
import { registerOfferTools } from "./offers.js";
import { registerCalendarEventTools } from "./calendar-events.js";
import { registerProductTools } from "./products.js";
import { registerProductCategoryTools } from "./product-categories.js";
import { registerProductFieldTools } from "./product-fields.js";
import { registerDashboardTools } from "./dashboards.js";
import { registerWebformTools } from "./webforms.js";
import { registerOfferTemplateTools } from "./offer-templates.js";
import { registerAfterOrderWorkTools } from "./after-order-work.js";
import { registerWebhookTools } from "./webhooks.js";
import { registerMessageTemplateTools } from "./message-templates.js";
import { registerCallTools } from "./calls.js";
import { registerCallTagTools } from "./call-tags.js";
import { registerDialGroupTools } from "./dial-groups.js";
import { registerChatTools } from "./chat.js";
import { registerUserMessageTools } from "./user-messages.js";
import { registerExternalOrderEventTools } from "./external-order-events.js";
import { registerStatisticsTools } from "./statistics.js";
import { registerExcludeListTools } from "./exclude-lists.js";
import { registerOrganizationTools } from "./organizations.js";
import { registerImpersonationTools } from "./impersonation.js";

export function registerAllTools(server: McpServer, api: ApiClient, config: Config) {
  registerAuthTools(server, api);
  registerUserTools(server, api);
  registerTeamTools(server, api);
  registerProjectTools(server, api);
  registerUserRoleTools(server, api);
  registerContactFieldTools(server, api);
  registerContactTagTools(server, api);
  registerOrderFieldTools(server, api);
  registerOrderTagTools(server, api);
  registerContactTools(server, api);
  registerOrderTools(server, api);
  registerOfferTools(server, api);
  registerCalendarEventTools(server, api);
  registerProductTools(server, api);
  registerProductCategoryTools(server, api);
  registerProductFieldTools(server, api);
  registerDashboardTools(server, api);
  registerWebformTools(server, api);
  registerOfferTemplateTools(server, api);
  registerAfterOrderWorkTools(server, api);
  registerWebhookTools(server, api);
  registerMessageTemplateTools(server, api);
  registerCallTools(server, api);
  registerCallTagTools(server, api);
  registerDialGroupTools(server, api);
  registerChatTools(server, api);
  registerUserMessageTools(server, api);
  registerExternalOrderEventTools(server, api);
  registerStatisticsTools(server, api);
  registerExcludeListTools(server, api);
  registerOrganizationTools(server, api, config);
  registerImpersonationTools(server, api, config);
}
